---
title: "Reading groups"
---

# Intro to LLMs


All information for this reading group available [here](https://llms-cunef-icmat-rg2024.github.io/)!


# Casual Inference and Machine Learning

These sessions take place on Fridays from 12.15 pm to 1.15 pm (CET). Each week a volunteer will briefly explain a chapter or paper (related to Causal Inference) to the rest of the audience in no more than 45 minutes (ideally less). In the last >15 minutes, we will discuss the topic explained. During the explanation, participants can ask questions. The sessions will be recorded and uploaded to the ICMAT youtube channel. You can find the video links below. Besides, you will find the necessary material for these sessions in the resources section.

More information on how to join online [here](https://datalab.icmat.es/bayesian-year/ciml/).


## Sessions

### 1

"Chapter 1: A definition of causal effect" from "Causal Inference. What If" book. Lecturer: [Roi Naveiro](https://roinaveiro.github.io/). December 2nd 2022. Click [here](https://www.youtube.com/watch?v=d7St2qwIeH0) to watch.


### 2

"Chapter 2: Randomized experiments" from "Causal Inference. What If" book. Lecturer: [David Ríos Insua](https://www.davidriosinsua.es/). December 16th 2022. Click [here](https://www.youtube.com/watch?v=TjrSCCwUZbU) to watch.


### 3

"Chapter 3: Observational studies" from "Causal Inference. What If" book. Lecturer: [Roi Naveiro](https://roinaveiro.github.io/). December 23rd 2022. Click [here](https://www.youtube.com/watch?v=9xQBApfKDxY&ab_channel=InstitutodeCienciasMatem%C3%A1ticasICMAT) to watch.


### 4

"Chapter 4: Effect modification" from "Causal Inference. What If" book. Lecturer: [Simón Rodríguez Santana](https://scholar.google.es/citations?user=9x_tXzwAAAAJ&hl=es). January 20th 2023. Click [here](https://www.youtube.com/watch?v=gHK2HszEKlM) to watch.

### 5

"Chapter 5: Interaction" from "Causal Inference. What If" book. Lecturer: [Jose M. Camacho](https://www.icmat.es/josemanuel.camacho). January 27th 2023. Click [here](https://www.youtube.com/watch?v=oLb71TDyXGg&t=2766s) to watch.

### 6

"Chapter 6: Graphical representation of causal effects" from "Causal Inference. What If" book.
 Lecturer: [David Ríos Insua](https://www.davidriosinsua.es/). February  3rd 2023. Click [here](https://www.youtube.com/watch?v=wPuJ8tR_05s&list=PLH_XnVAPg2hzUqt8f-NWlZZZi79BmU8Jt&index=2) to watch.


### 7

"Chapter 8: Selection bias" from "Causal Inference. What If" book.
 Lecturer: [Ramón Díaz Uriarte](https://www.ligarto.org/rdiaz/). February 10th 2023. Click [here](https://www.youtube.com/watch?v=JrjzHA1A-Ls) to watch.

### 8

"Chapter 7: Confounding" from "Causal Inference. What If" book.
 Lecturer: [Juan F. Poyatos](http://wwwuser.cnb.csic.es/~jpoyatos/Home/Home.html). February 17th 2023. Click [here](https://www.youtube.com/watch?v=I4k0I8R7R8A&t=1s) to watch.

### 9 

"Quantum information tools that deal with causality ". The session is based on: [[1](https://arxiv.org/abs/1609.00672)], [[2](https://arxiv.org/abs/1707.06476 )], [[3](https://arxiv.org/abs/1909.10519)].
Lecturer: [Alex Pozas](https://www.alexpozas.com/home). February 24th 2023. Click [here](https://www.youtube.com/watch?v=RCcEY6KJhaY&list=PLH_XnVAPg2hzUqt8f-NWlZZZi79BmU8Jt&index=1&t=6s) to watch.

### 10

"Chapter 9: Measurement bias" from "Causal Inference. What If" book.
 Lecturer: [Simón Rodríguez Santana](https://scholar.google.es/citations?user=9x_tXzwAAAAJ&hl=es). March 3rd 2023. Click [here](https://www.youtube.com/watch?v=ByVCDquxfCU) to watch.


### 11 

"Chapter 10: Random Variability" from "Causal Inference. What If" book.
 Lecturer: [Roi Naveiro](https://roinaveiro.github.io/). March 10th 2023. Click [here](https://www.youtube.com/watch?v=JVErPA-h3aM) to watch.
 
### 12 
 
"Casually (and causally?) playing with a large health database".
 Lecturer: [David Ríos Insua](https://www.davidriosinsua.es/). March 17th 2023. Click [here](https://www.youtube.com/watch?v=oE94JnvU5ek&list=PLH_XnVAPg2hwSIGIvgK7aCd0U0TYnblFq&index=1) to watch.
 
### 13

"Mendelian Randomization: Using genetic variability as an instrumental variable in Causal Inference". Lecturer: [Fátima Sánchez Cabo](https://www.cnic.es/es/fatima-sanchez-cabo-0). Friday 31st 2023. Click [here](https://www.youtube.com/watch?v=2LB20U9rvVc) to watch.

### Resources

In this section, you will find the neccessary material for the reading sessions.

* [Causal Inference. What If](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) book by Miguel Hernán and James M. Robins. 

* [Figures used in 2nd session](https://github.com/datalab-icmat/reading-groups/blob/main/material_session_2.pdf).

